import type { Metadata } from "next";
import { Rubik} from "next/font/google";
import "../../globals.css";
import { BottonMenu } from "@/components/BottomMenu";
import { cn } from "@/lib/utils";
import { ApplicationHeader } from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fontSans = Rubik({
  subsets: ["latin"],
  variable: "--font-sans",
})

export default function RootLayout({
  children,
  params: {locale}
}: Readonly<{
  children: React.ReactNode;
  params: {locale: string};
}>) {
  return (
    <html lang={locale} className="dark">
      <body className={cn(
          "min-h-screen bg-background font-sans antialiased text-white bg-app-background",
          fontSans.variable
        )}>
        <ApplicationHeader />
          {children}
        <BottonMenu />
    </body>
    </html>
  );
}
