import type { Metadata } from "next";
import "../../../globals.css";
import { ApplicationHeader } from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: {locale}
}: Readonly<{
  children: React.ReactNode;
  params: {locale: string};
}>) {
  return (
    <div>
      <ApplicationHeader hideMenu />
      {children}
    </div>
  );
}
