import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";
import { cn } from "../../lib/utils";
import { NextIntlClientProvider, useMessages } from 'next-intl';
import { Toaster } from "@/components/ui/toaster";
import { AuthProvider } from "@/context/auth-context";
import { cookies } from "next/headers"
import {  DrawerProvider } from "@/context/drawer-context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fontSans = Rubik({
  subsets: ["latin"],
  variable: "--font-sans",
})

export default function RootLayout({
  children,
  params: {locale}
}: Readonly<{
  children: React.ReactNode;
  params: {locale: string};
}>) {
  const messages = useMessages();

  async function  loadToken(){
    const token = cookies().get('session')?.value
    return token
  }
  

  return (
    <html lang={locale} className="dark">
      <body className={cn(
          "min-h-screen bg-background font-sans antialiased text-white bg-app-background",
          fontSans.variable
        )}>

      <AuthProvider token={loadToken()} >
        <DrawerProvider>
          <NextIntlClientProvider locale={locale} messages={messages}>
              {children}
          </NextIntlClientProvider>
          
          <Toaster />
        </DrawerProvider>
      </AuthProvider>

    </body>
    </html>
  );
}
